# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa93c9b9b8260c46b2dab99819ea82a63c177c419504359ebe663d66877814d60da80e3d3babe7e517b9c655915ce832aa388d526e27c311ba37af020269b2b4

test:
  secret_key_base: 852c05b09b2c80c539218109d8eabc7c2ad0957c9470851a73efa0bfe5e9fa48b1e58c039a970172ba51d28c1a4a36349acc0c1e7c7681fc59a4cb7a17247605

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
